/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *
add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x + argp->y;
	printf("Soma: %d\n", result);

	return &result;
}

int *
sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x - argp->y;
	printf("Subtracao: %d\n", result);

	return &result;
}

int *
mul_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x * argp->y;
	printf("Multiplicacao: %d\n", result);

	return &result;
}

int *
div_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	if(argp->y != 0) {
		result = argp->x / argp->y;
		printf("Divisao: %d\n", result);
	} else {
		printf("Divisao: Valores invalidos\n");
		result = 0;
	}

	return &result;
}
