/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"


void
prog_100(char *host, char *operand_1, char *operand_2, char *signal)
{
	CLIENT *clnt;

	int  *result;

	operandos operands;

	/*Conversao dos operadores para inteiro*/
	operands.x = atoi(operand_1);
	operands.y = atoi(operand_2);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/*Selecao da operacao a ser executada*/
	switch (*signal) {
		case '+':
			result = add_100(&operands, clnt);
			printf("\n%d + %d = ", operands.x, operands.y);
			break;
		case '-':
			result = sub_100(&operands, clnt);
			printf("\n%d - %d = ", operands.x, operands.y);
			break;
		case '*':
			result = mul_100(&operands, clnt);
			printf("\n%d * %d = ", operands.x, operands.y);
			break;
		case '/':
			result = div_100(&operands, clnt);
			printf("\n");
			if(operands.y == 0) printf("Operacao Invalida\n");
			printf("%d / %d = ", operands.x, operands.y);
			break;
		default:
			printf("Operacao Invalida\n");
			return;
			break;
	}

	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}	else {
		printf("%d\n\n", *result);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host operand_1 signal operand_2\n", argv[0]);
		exit (1);
	}

	printf("Para correto funcionamento da Multiplicacao utilize o operador \\*\n\n");

	host = argv[1];

	prog_100 (host, argv[2], argv[4], argv[3]);

}
